# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'TestAppCenterDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestAppCenterDemo
  pod 'AppCenter'

  target 'TestAppCenterDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'AppCenter'
  end

  target 'TestAppCenterDemoUITests' do
    inherit! :search_paths
    pod 'AppCenter'
    # Pods for testing
  end

end
